### ISSUE TITLE
Hook 'colors' or 'sd-colors' cannot be found

### ISSUE THREAD

**Issue by stevensonmt** [evanpurkhiser/mkinitcpio-colors#12]
After installing via AUR on Arch Linux I edited `vconsole.conf` with my colorscheme and then added 'colors' to the `HOOKS` in `mkinitcpio.conf`. This generated the error in the title so I changed it to `sd-colors` and had the same result. The `HOOKS` line from my `mkinitcpio.conf` file is this:
>HOOKS="base udev autodetect colors keyboard keymap consolefont modconf block lvm2 filesystems fsck"

When I tried to enable setcolors.service as a systemd unit I got the error `Failed to enable unit: Unit file setcolors.service does not exist.`

==================
I think this is an issue with AUR package actually. By manually installing from the github repo everything works. It seems the only thing the AUR package installs is `linux-vt-setcolors`. I didn't see any issues with the PKGBUILD file so it may be some permissions problem on my system.

**Comment by evanpurkhiser** [comment]
Did you manage to resolve this?

**Comment by GaKu999** [comment]
> Did you manage to resolve this?

Seems to be just a minor case of confusion, the AUR link was mistakenly for the dependency instead of this one, and since OP discovered this here, only setcolors-git was installed.

**Comment by GaKu999** [comment]
Guess I derped that in #11
