### ISSUE TITLE
Automatically registering the hook

### ISSUE THREAD

**Issue by es20490446e** [EvanPurkhiser/mkinitcpio-colors#6]
The following [script](https://pastebin.com/ackc7dGK) registers the colors hook, automatically and safely.

It works despite of the current hook list. And if the hook is already there, it isn't added.

**Comment by GaKu999** [comment]
Automatic configuration is up to downstream, this repository doesn't even provide a PKGBUILD.
Closing, because it is out of the scope of this repository.
